# Generated by Django 5.0.1 on 2024-03-20 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_stat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='Дата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_product', to='blog.product', verbose_name='Товары')),
                ('stat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_stat', to='blog.stat', verbose_name='Статус')),
            ],
        ),
    ]
