# Generated by Django 5.0.1 on 2024-03-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_orders_created_alter_orders_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_product', to='blog.product', verbose_name='Товары'),
        ),
    ]
